name: Debugger Workflow

on:
  push:
    branches:
      - '**'

env:
  ENVIRONMENT_NAME: ${{
    startsWith(github.ref_name, vars.BRANCH_STG1) && 'STG1' ||
    startsWith(github.ref_name, vars.BRANCH_STG2) && 'STG2' ||
    startsWith(github.ref_name, vars.BRANCH_STG3) && 'STG3'
    }}

concurrency: 
  group: group-${{ 
    startsWith(github.ref_name, vars.BRANCH_STG1) && 'group-STG1' || 
    startsWith(github.ref_name, vars.BRANCH_STG2) && 'group-STG2' || 
    startsWith(github.ref_name, vars.BRANCH_STG3) && 'group-STG3' ||
    group-unknown
    }}

jobs:
  show-variables-and-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Add repository variables to summary
        run: |
          echo "### Repository Variables Values" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG1: ${{ vars.BRANCH_STG1 }}" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG2: ${{ vars.BRANCH_STG2 }}" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG3: ${{ vars.BRANCH_STG3 }}" >> $GITHUB_STEP_SUMMARY

      - name: Validate Environment Variable
        run: |
          if [[ "${{ env.ENVIRONMENT_NAME }}" != "STG1" && "${{ env.ENVIRONMENT_NAME }}" != "STG2" && "${{ env.ENVIRONMENT_NAME }}" != "STG3" ]]; then
            echo "A branch that is being used is not being targeted to any environment: Update the BRANCH_STGX repository variable that best applies to this merge." >> $GITHUB_STEP_SUMMARY
          exit 1
          fi

      - name: Show Environment
        run: |
          echo "### Environment" >> $GITHUB_STEP_SUMMARY
          echo "ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}" >> $GITHUB_STEP_SUMMARY


# A branch that is being used is not being targeted to any environment: Update the BRANCH_STGX repository variable that best applies to this merge.
