name: Debugger Workflow

on:
  push:
    branches:
      - '**'

env:
  ENVIRONMENT_NAME: ${{ startsWith(github.ref_name, vars.BRANCH_STG1) && 'STG1' ||
    startsWith(github.ref_name, vars.BRANCH_STG2) && 'STG2' ||
    startsWith(github.ref_name, vars.BRANCH_STG3) && 'STG3' ||
    }}

concurrency: 
  group: ${{ 
    startsWith(github.ref_name, vars.BRANCH_STG1) && 'group-STG1' || 
    (startsWith(github.ref_name, vars.BRANCH_STG2) || startsWith(github.ref_name, 'patch')) && 'group-STG2' || 
    (startsWith(github.ref_name, vars.BRANCH_STG3) || github.ref_name == 'master' || github.ref_name == 'main') && 'group-STG3' || 
    'unknown-group' 
    }}

jobs:
  show-variables-and-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Add repository variables to summary
        run: |
          echo "### Repository Variables Values" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG1: ${{ vars.BRANCH_STG1 }}" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG2: ${{ vars.BRANCH_STG2 }}" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG3: ${{ vars.BRANCH_STG3 }}" >> $GITHUB_STEP_SUMMARY

      - name: Show selected concurrency group
        run: |
          echo "### Selected Concurrency Group" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ startsWith(github.ref_name, vars.BRANCH_STG1) }}" == "true" ]]; then
            echo "Concurrency Group: group-STG1" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ startsWith(github.ref_name, vars.BRANCH_STG2) }}" == "true" || "${{ startsWith(github.ref_name, 'patch') }}" == "true" ]]; then
            echo "Concurrency Group: group-STG2" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ startsWith(github.ref_name, vars.BRANCH_STG3) }}" == "true" || "${{ github.ref_name }}" == "master" || "${{ github.ref_name }}" == "main" ]]; then
            echo "Concurrency Group: group-STG3" >> $GITHUB_STEP_SUMMARY
          else
            echo "Concurrency Group: unknown-group" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Show env variables
        run: |
          echo "### Environment Variables" >> $GITHUB_STEP_SUMMARY
          echo "ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}" >> $GITHUB_STEP_SUMMARY


