name: Debugger Workflow

on:
  push:
    branches:
      - '**'

env:
  ENVIRONMENT_NAME: ${{
    startsWith(github.ref_name, vars.BRANCH_STG1) && 'STG-1' ||
    startsWith(github.ref_name, vars.BRANCH_STG2) && 'STG-2' ||
    startsWith(github.ref_name, vars.BRANCH_STG3) && 'STG-3'
    }}

concurrency: 
  group: group-${{ 
    startsWith(github.ref_name, vars.BRANCH_STG1) && 'STG-1' || 
    startsWith(github.ref_name, vars.BRANCH_STG2) && 'STG-2' || 
    startsWith(github.ref_name, vars.BRANCH_STG3) && 'STG-3'
    }}

jobs:
  show-variables-and-concurrency:
    runs-on: windows-latest   
    environment: ${{
      startsWith(github.ref_name, vars.BRANCH_STG1) && 'STG-1' ||
      startsWith(github.ref_name, vars.BRANCH_STG2) && 'STG-2' ||
      startsWith(github.ref_name, vars.BRANCH_STG3) && 'STG-3'
      }}
    steps:
      - name: Add repository variables to summary
        run: |
          echo "### Repository Variables Values" >> $env:GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG1: ${{ vars.BRANCH_STG1 }}" >> $env:GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG2: ${{ vars.BRANCH_STG2 }}" >> $env:GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG3: ${{ vars.BRANCH_STG3 }}" >> $env:GITHUB_STEP_SUMMARY

      - name: Validate Environment Variable 
        run: |
          if [[ "${{ env.ENVIRONMENT_NAME }}" != "STG-1" && "${{ env.ENVIRONMENT_NAME }}" != "STG-2" && "${{ env.ENVIRONMENT_NAME }}" != "STG-3" ]]; then
            echo "### Error setting environment :x:" >> $env:GITHUB_STEP_SUMMARY
            echo "A branch that is being used is not being targeted to any environment: Update the BRANCH_STGX repository variable that best applies to this merge." >> $env:GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Show Environment
        run: |
          echo "### Environment" >> $env:GITHUB_STEP_SUMMARY
          echo "ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}" >> $env:GITHUB_STEP_SUMMARY
