name: Debugger Workflow

on:
  push:
    branches:
      - '**'

concurrency: 
  group: ${{ 
    startsWith(github.ref_name, vars.BRANCH_STG1) && 'group-STG1' || 
    (startsWith(github.ref_name, vars.BRANCH_STG2) || startsWith(github.ref_name, 'patch')) && 'group-STG2' || 
    (startsWith(github.ref_name, vars.BRANCH_STG3) || github.ref_name == 'master' || github.ref_name == 'main') && 'group-STG3' || 
    'unknown-group' 
    }}

jobs:
  show-variables-and-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Add repository variables to summary
        run: |
          echo "### Repository Variables Values" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG1: ${{ env.BRANCH_STG1 }}" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG2: ${{ env.BRANCH_STG2 }}" >> $GITHUB_STEP_SUMMARY
          echo "- BRANCH_STG3: ${{ env.BRANCH_STG3 }}" >> $GITHUB_STEP_SUMMARY

      - name: Show selected concurrency group
        run: |
          echo "### Selected Concurrency Group" >> $GITHUB_STEP_SUMMARY
          echo "Selected Concurrency Group: ${{ github.workflow_concurrency }}" >> $GITHUB_STEP_SUMMARY